import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
    // END: FlutterFire Configuration
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
}

println("flutter.minSdkVersion: ${flutter.minSdkVersion}")
println("flutter.targetSdkVersion: ${flutter.targetSdkVersion}")
println("flutter.compileSdkVersion: ${flutter.compileSdkVersion}")

android {
    signingConfigs {
        create("internal") {
            val keystoreProperties = Properties()
            val keystorePropertiesFile = rootProject.file("ecocotest_key.properties")
            if (keystorePropertiesFile.exists()) {
                keystoreProperties.load(FileInputStream(keystorePropertiesFile))
            }

            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = keystoreProperties["storeFile"]?.let { file(it as String) }
            storePassword = keystoreProperties["storePassword"] as String?
        }

        create("production") {
            val keystoreProperties = Properties()
            val keystorePropertiesFile = rootProject.file("ecoco_key.properties")
            if (keystorePropertiesFile.exists()) {
                keystoreProperties.load(FileInputStream(keystorePropertiesFile))
            }

            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = keystoreProperties["storeFile"]?.let { file(it as String) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }

    namespace = "com.ECOCO.ECOCO"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    // ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
    flavorDimensions += "default"

    productFlavors {
        create("mock") {
            dimension = "default"
            applicationId = "com.ECOCO.ECOCO.Test"
            signingConfig = signingConfigs.getByName("internal")
            resValue(
                type = "string",
                name = "app_name",
                value = "ECOCO 獨享版")
        }
        create("internal") {
            dimension = "default"
            applicationId = "com.ECOCO.ECOCO.Test"
            signingConfig = signingConfigs.getByName("internal")
            resValue(
                type = "string",
                name = "app_name",
                value = "ECOCO Test")
        }
        create("production") {
            dimension = "default"
            applicationId = "com.ECOCO.ECOCO"
            signingConfig = signingConfigs.getByName("production")
            resValue(
                type = "string",
                name = "app_name",
                value = "ECOCO")
        }
    }

    // ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        isCoreLibraryDesugaringEnabled = true
    }

    defaultConfig {
        applicationId = "com.ECOCO.ECOCO"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }
}

flutter {
    source = "../.."
}

dependencies {
    //val lifecycle_version = "2.9.3"

    implementation(platform("com.google.firebase:firebase-bom:34.4.0"))
    implementation("com.google.firebase:firebase-database")
    implementation("com.google.firebase:firebase-crashlytics-ndk")
    implementation("com.google.firebase:firebase-analytics")
    implementation("androidx.work:work-runtime-ktx:2.10.5")
    implementation("com.google.android.gms:play-services-maps:19.0.0")
    //implementation("androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version")
    //implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version")

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
}
